---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: pipeline
type: docker
name: linting
steps:
- name: prepare
  image: node:16-alpine3.16
  commands:
  - npm ci
- name: lint
  image: node:16-alpine3.16
  commands:
    - npm run lint:js
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: kFTFHNRinHlXtmuW7DOgq4hOioxOYBD3TsRtgflLjjzn9s+MYDpCKg==
---
kind: secret
name: docker_password
data: k6/jVP0O3wC04GqlYHmQkRDdEW72HUWNAruocB7yI5achtNiJrlCoGm746lq7Yi5IzL5JKS/mykvzDyl6E7hag==
---
kind: secret
name: docker_username
data: sEZZO1rkxpruC4SI7LPf54wyEnm/bD3F/AwUNSfp984WKlKuM6eDRA==
---
kind: secret
name: docker_password
data: eioqgGwIBAiGMg4Hw9uf4ZHQUcRP4JpEtG2jFSqrDl3nv407MyHNT9CDuKWw5LJ8jF62VQ1Ss2FYxrnKd2qAOg==
---
kind: signature
hmac: a6542888de09139918102a8bfaa31d8a344f8e5204739d0d7fb7bc00f2792338

...
