steps:
  build-feature:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: ${CI_COMMIT_BRANCH/\//-}
      platforms: linux/amd64
    secrets: [ docker_username, docker_password ]
when:
  branch: feature/*
  event: push