steps:
  build-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: "${CI_COMMIT_TAG##v}" # drops v from version tag
      platforms: linux/amd64
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  ref: refs/tags/v*